### PR TITLE
Fix #91 : Display all layers in the catalog

### LINKED ISSUE #91: Display all emapis layers int the catalog
@AFoletti waht is the status of emapis layers are they all available in your branch of chsdi?

### PR DESCRIPTION
**Pull request by kandre**
Fix #91

### CODE REVIEW

**Comment by kandre** [comment]
PR is ready for review/merge

**Comment by oterral** [comment]
@kandre translations are missing can you add it pls?

**Comment by kandre** [comment]
Yes of course. But that's part of integration process, which is not completed right?

**Comment by kandre** [comment]
Thanks !

**Pull request merged**
